<<<<<<< HEAD
const REG = 55; const HAR = 75; const DIRE = 65; const MADA = 60;

export const universities = [
  { name: "Oda Bultum University", max: REG},
  { name: "Adama Science and Technology University", max: REG },
  { name: "Addis Ababa Science and Technology University", max: REG },
  { name: "Addis Ababa University", max: REG},
  { name: "Adigrat University", max: REG },
  { name: "Ambo University", max: REG },
  { name: "Arba Minch University", max: REG },
  { name: "Assosa University", max: REG },
  { name: "Arsi University", max: REG },
  { name: "Axum University", max: REG },
  { name: "Bahir Dar University", max: REG },
  { name: "Borena University Ethiopia", max: REG },
  { name: "Bule Hora University", max: REG },
  { name: "Bonga University", max: REG },
  { name: "Civil Service University", max: REG },
  { name: "Debre Berhan University", max: REG },
  { name: "Debre Markos University", max: REG },
  { name: "Debre Tabor University", max: REG },
  { name: "Dembi Dolo University", max: REG },
  { name: "Debark University", max: REG },
  { name: "Dilla University", max: REG },
  { name: "Dire Dawa University", max: DIRE },
  { name: "FDRE Technical & Vocational Training Institute", max: REG },
  { name: "Gambella University", max: REG },
  { name: "Gondor University", max: REG },
  { name: "Haramaya University", max: HAR },
  { name: "Hawassa University", max: REG },
  { name: "Injibara University", max: REG },
  { name: "Jigjiga University", max: REG },
  { name: "Jimma University", max: REG },
  { name: "Jinka University", max: REG },
  { name: "Kebri Dahar University", max: REG },
  { name: "Kotebe University", max: REG },
  { name: "Madda Walabu University", max: MADA },
  { name: "Mattu University", max: REG },
  { name: "Mekdela Amba University", max: REG },
  { name: "Mekelle University", max: REG },
  { name: "Mekelakeya University Ethiopia", max: REG },
  { name: "Mizan–Tepi University", max: REG },
  { name: "Raya University", max: REG },
  { name: "Samara University", max: REG },
  { name: "Salale University", max: REG },
  { name: "Wachamo University", max: REG },
  { name: "Werabe University", max: REG },
  { name: "Woldia University", max: REG },
  { name: "Wolkite University", max: REG },
  { name: "Wolaita Sodo University", max: REG },
  { name: "Wollega University", max: REG },
  { name: "Wollo University", max: REG },
];
=======
export const universities = [
    "Oda Bultum University",
    "Adama Science and Technology University",
    "Addis Ababa Science and Technology University",
    "Addis Ababa University",
    "Adigrat University",
    "Ambo University",
    "Arba Minch University",
    "Assosa University",
    "Arsi University",
    "Axum University",
    "Bahir Dar University",
    "Bule Hora University",
    "Bonga University",
    "Civil Service University",
    "Debre Berhan University",
    "Debre Markos University",
    "Debre Tabor University",
    "Dembi Dolo University",
    "Debark University",
    "Dilla University",
    "Dire Dawa University",
    "Ethiopia Teqinuqe universtiy",
    "Gambella University",
    "Gondor University",
    "Haramaya University",
    "Hawassa University",
    "Injibara University",
    "Jigjiga University",
    "Jimma University",
    "Jinka University",
    "Kebri Dahar University",
    "Kotebe University of Education",
    "Madda Walabu University",
    "Mattu University",
    "Mekdela Amba University",
    "Mekelle University",
    "Mekelakeya University Ethiopia",
    "Mizan–Tepi University",
    "Raya University",
    "Samara University",
    "Salale University",
    "Wachamo University",
    "Werabe University",
    "Woldia University",
    "Wolkite University",
    "Wolaita Sodo University",
    "Wollega University",
    "Wollo University",
  ];
>>>>>>> 54171a1 (Final-V2)
